### ISSUE TITLE
Файл hello_world.trigger

### ISSUE THREAD

**Issue by vantu5z** [Oknolaz/vasisualy#10]
Отсутствует файл `hello_world.trigger` в пакете. Из-за чего вылетает ошибка:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vasisualy/main.py", line 68, in vasmsg
    self.program()
  File "/usr/lib/python3.9/site-packages/vasisualy/main.py", line 100, in program
    elif skill_loader.run_skills(say, self.listWidget):
  File "/usr/lib/python3.9/site-packages/vasisualy/skills/skill_loader.py", line 56, in run_skills
    result = sys.modules[skill].main(user_message)
  File "/usr/lib/python3.9/site-packages/vasisualy/skills/hello_world/__init__.py", line 14, in main
    return skill.main(user_message)
  File "/usr/lib/python3.9/site-packages/vasisualy/skills/hello_world/__init__.py", line 6, in main
    if super(HelloWorld, self)._is_triggered(user_message, super(HelloWorld, self)._get_triggers()):
  File "/usr/lib/python3.9/site-packages/vasisualy/skills/vas_skill/vas_skill.py", line 19, in _get_triggers
    file = open(f"{str(Path(self.root))}/{self.name}.trigger")
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/usr/lib/python3.9/site-packages/vasisualy/skills/hello_world/hello_world.trigger'
```
Предполагаю, что нужно добавить это файл в `setup.py` в список `package_data`.

**Comment by Oknolaz** [comment]
`setup.py` был изменён, теперь ошибки быть не должно.

**Comment by vantu5z** [comment]
Оперативненько :)
Да, всё заработало.
